# -*- coding: utf-8 -*-
"""Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cZ5zV_kybHhoo8xhu_FN_1IM8BkYk4-
"""

!pip install nistrng

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
import numpy as np
from scipy.stats import laplace, norm, uniform, bernoulli, kurtosis, skew, shapiro
from sklearn.metrics import accuracy_score
import random
import hashlib
import time

# For NIST randomness tests
from nistrng import run_all_battery, SP800_22R1A_BATTERY

# Load CIFAR-10 dataset
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

train_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=64, shuffle=False)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
# Load a pre-trained ResNet18 model and modify it for CIFAR-10
model = models.resnet18(pretrained=True)
model.fc = nn.Linear(model.fc.in_features, 10)  # Change output layer for 10 classes
model = model.to(device)

def randomised_smoothing(model, x, n_samples, prng, noise_distribution):
    """
    Certify robustness using randomised smoothing with alternative noise distributions.
    :param model: Trained model.
    :param x: Input sample.
    :param n_samples: Number of noise samples.
    :param prng: Random number generator (standard or cryptographic).
    :param noise_distribution: Type of noise distribution ('laplace', 'abs_normal', 'uniform', 'bernoulli').
    :return: Certified robustness radius and predicted class.
    """
    model.eval()
    counts = np.zeros(10)
    # Get the original shape of the input
    original_shape = x.shape
    # Reshape to remove the batch size, if more than 2 dimensions
    # Iterate through each image in the batch
    for i in range(x.shape[0]):
        single_image = x[i]
        if len(single_image.shape) > 2:
            # Reshape the single image to (3, 32, 32)
            single_image = single_image.reshape(single_image.shape[-3], single_image.shape[-2], single_image.shape[-1])

        for _ in range(n_samples):
            if noise_distribution == 'laplace':
                noise = laplace.rvs(loc=0, scale=0.25, size=single_image.shape).astype(np.float32)
            elif noise_distribution == 'abs_normal':
                noise = np.abs(norm.rvs(loc=0, scale=0.25, size=single_image.shape)).astype(np.float32)
            elif noise_distribution == 'uniform':
                noise = uniform.rvs(loc=-0.25, scale=0.5, size=single_image.shape).astype(np.float32)
            elif noise_distribution == 'bernoulli':
                noise = bernoulli.rvs(0.5, size=single_image.shape).astype(np.float32) - 0.5
            else:
                raise ValueError("Invalid noise distribution.")

            noisy_input = single_image + noise
            noisy_input = torch.from_numpy(noisy_input).unsqueeze(0).to(device)
            output = model(noisy_input)
            pred = torch.argmax(output, dim=1).item()
            counts[pred] += 1

    predicted_class = np.argmax(counts)
    p_a = counts[predicted_class] / n_samples
    radius = 0.25 * norm.ppf(p_a)  # we can adjust radius based on noise distribution
    return radius, predicted_class

#PRNG-Based Attack Simulation (Bit-Flipping PRNG Attacker)

def generate_attack_noise(shape, attack_type):
    """
    Generate attack noise with specific statistical properties.
    :param shape: Shape of the noise.
    :param attack_type: Type of attack ('positive_kurtosis', 'negative_kurtosis', 'skewness').
    :return: Attack noise.
    """
    if attack_type == 'positive_kurtosis':
        # High kurtosis (heavy-tailed distribution)
        noise = np.random.standard_t(3, size=shape)
    elif attack_type == 'negative_kurtosis':
        # Low kurtosis (light-tailed distribution)
        noise = np.random.uniform(-1, 1, size=shape)
    elif attack_type == 'skewness':
        # Skewed distribution
        noise = np.random.exponential(1, size=shape) - 1
    else:
        raise ValueError("Invalid attack type.")
    return noise.astype(np.float32)

def bit_flip_attack(prng_state, bit_position):
    """
    Simulate a bit-flipping attack on the PRNG state.
    :param prng_state: Current state of the PRNG.
    :param bit_position: Position of the bit to flip.
    :return: Modified PRNG state.
    """
    prng_state[bit_position // 8] ^= 1 << (bit_position % 8)
    return prng_state

def prng_based_attack(model, x, n_samples, prng, attack_type, target_class, bit_position=None):
    """
    Simulate a PRNG-based adversarial attack with specific statistical properties.
    :param model: Trained model.
    :param x: Input sample.
    :param n_samples: Number of noise samples.
    :param prng: Random number generator (standard or cryptographic).
    :param attack_type: Type of attack ('positive_kurtosis', 'negative_kurtosis', 'skewness').
    :param target_class: Target class for the attack.
    :param bit_position: Position of the bit to flip (for bit-flipping attack).
    :return: Attack success rate.
    """
    success = 0
    for _ in range(n_samples):
        if bit_position is not None:
            # Perform bit-flipping attack
            prng_state = np.random.get_state()[1].copy()
            prng_state = bit_flip_attack(prng_state, bit_position)
            np.random.set_state((np.random.get_state()[0], prng_state, *np.random.get_state()[2:]))

        base_noise = prng.normal(0, 0.25, size=x.shape).astype(np.float32)
        attack_noise = generate_attack_noise(x.shape, attack_type)
        noisy_input = x + base_noise + attack_noise
        noisy_input = torch.from_numpy(noisy_input).unsqueeze(0).to(device)
        output = model(noisy_input)
        pred = torch.argmax(output, dim=1).item()
        if pred == target_class:
            success += 1

    attack_success_rate = success / n_samples
    return attack_success_rate

# Randomness Quality Evaluation
# NIST Test

def nist_test(samples):
    """
    Evaluate randomness quality using NIST statistical tests.
    :param samples: Randomness samples.
    :return: NIST test results.
    """
    samples = [1 if s >= 0.5 else 0 for s in samples]
    # Convert the list of samples to a NumPy array before passing to run_all_battery
    samples = np.array(samples)
    results = run_all_battery(samples, SP800_22R1A_BATTERY)
    return results

# Shapiro-Wilk Test
def shapiro_wilk_test(samples):
    """
    Evaluate randomness quality using the Shapiro-Wilk test.
    :param samples: Randomness samples.
    :return: Shapiro-Wilk test statistic and p-value.
    """
    stat, p_value = shapiro(samples)
    return stat, p_value

# Certified Robustness Calculation

def certify_robustness(model, test_loader, n_samples, prng, noise_distribution):
    """
    Calculate certified robustness for the entire test dataset.
    :param model: Trained model.
    :param test_loader: Test dataset loader.
    :param n_samples: Number of noise samples.
    :param prng: Random number generator (standard or cryptographic).
    :param noise_distribution: Type of noise distribution ('laplace', 'abs_normal', 'uniform', 'bernoulli').
    :return: Average certified robustness radius.
    """
    radii = []
    for x, _ in test_loader:
        x = x.numpy()
        radius, _ = randomised_smoothing(model, x, n_samples, prng, noise_distribution)
        radii.append(radius)
    return np.mean(radii)

# Evaluation Metrics Computation

def evaluate_model(model, test_loader, prng, noise_distribution, bit_position=None):
    """
    Evaluate model performance and robustness.
    :param model: Trained model.
    :param test_loader: Test dataset loader.
    :param prng: Random number generator (standard or cryptographic).
    :param noise_distribution: Type of noise distribution ('laplace', 'abs_normal', 'uniform', 'bernoulli').
    :param bit_position: Position of the bit to flip (for bit-flipping attack).
    :return: Clean accuracy, certified robustness, and attack success rates.
    """
    # Clean accuracy
    y_true, y_pred = [], []
    for x, y in test_loader:
        x, y = x.to(device), y.to(device)
        output = model(x)
        pred = torch.argmax(output, dim=1)
        y_true.extend(y.cpu().numpy())
        y_pred.extend(pred.cpu().numpy())
    clean_accuracy = accuracy_score(y_true, y_pred)

    # Certified robustness
    n_samples = 2
    certified_robustness = certify_robustness(model, test_loader, n_samples, prng, noise_distribution)

    # Attack success rates
    target_class = 0
    x, _ = next(iter(test_loader))
    x = x[0].numpy()  # here we use the first test sample for the attack
    attack_types = ['positive_kurtosis', 'negative_kurtosis', 'skewness']
    attack_success_rates = {}
    for attack_type in attack_types:
        attack_success_rates[attack_type] = prng_based_attack(model, x, n_samples, prng, attack_type, target_class, bit_position)

    return clean_accuracy, certified_robustness, attack_success_rates

# Main Execution

if __name__ == "__main__":
    # Train the model (omitted for brevity)
    # model = train_model(train_loader)

    # Define PRNGs
    standard_prng = np.random.RandomState(42)
    seed = int.from_bytes(hashlib.sha256(b"seed").digest(), 'big')
    cryptographic_prng = np.random.Generator(np.random.SFC64(seed))

    # Evaluate randomness quality
    samples = cryptographic_prng.random(5000)
    nist_results = nist_test(samples)
    shapiro_stat, shapiro_p_value = shapiro_wilk_test(samples)
    print("NIST Test Results:", nist_results)
    print("Shapiro-Wilk Test Results: Statistic =", shapiro_stat, "P-value =", shapiro_p_value)

    # Evaluate model with standard PRNG and alternative noise distributions
    noise_distributions = ['laplace', 'abs_normal', 'uniform', 'bernoulli']
    for noise_dist in noise_distributions:
        clean_accuracy, certified_robustness, attack_success_rates = evaluate_model(model, test_loader, standard_prng, noise_dist, bit_position=10)
        print(f"Standard PRNG ({noise_dist}) - Clean Accuracy: {clean_accuracy}, Certified Robustness: {certified_robustness}")
        for attack_type, rate in attack_success_rates.items():
            print(f"Attack Success Rate ({attack_type}): {rate}")

    # Evaluate model with cryptographic PRNG and alternative noise distributions
    for noise_dist in noise_distributions:
        clean_accuracy, certified_robustness, attack_success_rates = evaluate_model(model, test_loader, cryptographic_prng, noise_dist, bit_position=10)
        print(f"Cryptographic PRNG ({noise_dist}) - Clean Accuracy: {clean_accuracy}, Certified Robustness: {certified_robustness}")
        for attack_type, rate in attack_success_rates.items():
            print(f"Attack Success Rate ({attack_type}): {rate}")

